- src/main/java/muramasa/antimatter/materials/Element.java
Added the correct names for elements 113, 115, 117 and 118.
> Updated Element.java

- build.gradle
Fixes run data always dumping the output into current project src rather than own project
> Fix runData

- src/main/java/muramasa/antimatter/Antimatter.java
- src/main/java/muramasa/antimatter/recipe/condition/ConfigCondition.java
For conditional recipes. (config)
Note: this will not crash, but throw an error in console at ServerStart if a field (rarely a class) isn't found.
> Added ConfigCondition (ICondition)

- src/main/java/muramasa/antimatter/materials/Material.java
- Uses ImmutableMap instead
- ImmutableMap#Builder for anything above 5 elements
> Changed way to add MaterialStack (chemical formula)

- src/main/java/muramasa/antimatter/Data.java
- src/main/java/muramasa/antimatter/behaviour/IBehaviour.java
- src/main/java/muramasa/antimatter/behaviour/IBlockDestroyed.java
- src/main/java/muramasa/antimatter/behaviour/IItemUse.java
- src/main/java/muramasa/antimatter/tools/base/MaterialTool.java
- src/main/java/muramasa/antimatter/tools/behaviour/BehaviourAOEBreak.java
- src/main/java/muramasa/antimatter/tools/behaviour/BehaviourBlockRotate.java
- src/main/java/muramasa/antimatter/tools/behaviour/BehaviourBlockTilling.java
- src/main/java/muramasa/antimatter/tools/behaviour/BehaviourLogStripping.java
- src/main/java/muramasa/antimatter/tools/behaviour/BehaviourPoweredDebug.java
- src/main/java/muramasa/antimatter/tools/behaviour/BehaviourTreeFelling.java
- src/main/java/muramasa/antimatter/tools/behaviour/BehaviourWaterlogToggle.java
- Currently for IBlockDestroyed and IItemUse only
- Implemented hoe and shovel behaviours
> Made behaviours FunctionalInterfaces

- src/main/java/muramasa/antimatter/capability/impl/ItemStackWrapper.java
- src/main/java/muramasa/antimatter/capability/impl/MachineItemHandler.java
Or you could use Mojang's Pair. Your choice!
> Use Apache Commons Pair instead of JavaFX's

- src/main/java/muramasa/antimatter/capability/impl/CoverHandler.java
- src/main/java/muramasa/antimatter/cover/Cover.java
- src/main/java/muramasa/antimatter/item/ItemCover.java
- src/main/java/muramasa/antimatter/tesseract/EnergyTileWrapper.java
- src/main/java/muramasa/antimatter/tesseract/FluidTileWrapper.java
- src/main/java/muramasa/antimatter/tesseract/ItemTileWrapper.java
- src/main/java/muramasa/antimatter/tool/AntimatterToolType.java
Default utils replaced by fastutils
Added coverable capability to the cover item
> Small refactoring

- build.gradle
- This allows for src lookup any time, even during debug (finally)
- I'll write a better buildscript later...
- P.S - add src jar to path when IDEA tells you to (after you build once)
> Fixed src path/jar not being able to be found

- src/main/java/muramasa/antimatter/Data.java
- src/main/java/muramasa/antimatter/tool/AntimatterToolType.java
- src/main/java/muramasa/antimatter/tool/IAntimatterTool.java
- Added a ctor that allows initialising base values with an existing AntimatterToolType
- Remove redundant Nonnull annotations
> Fixed some tool values

- src/main/java/muramasa/antimatter/client/event/ClientEvents.java
- src/main/java/muramasa/antimatter/datagen/providers/AntimatterItemModelProvider.java
- src/main/java/muramasa/antimatter/datagen/providers/AntimatterItemTagProvider.java
- src/main/java/muramasa/antimatter/registration/RegistrationHelper.java
- src/main/java/muramasa/antimatter/tool/IAntimatterTool.java
- src/main/java/muramasa/antimatter/tool/MaterialSword.java
- src/main/java/muramasa/antimatter/tool/MaterialTool.java
- Cleaned tool stuff up a bit more
- Use IForgeItem's getItem(), big brain mode
- Generified fillItemGroup
> If you can't beat 'em, join 'em

- src/main/java/muramasa/antimatter/capability/impl/ItemEnergyHandler.java
just minor fix so that discharge disabling doesnt block input
> Bugfix discharge

- src/main/java/muramasa/antimatter/machine/BlockMachine.java
Add blockstates to BlockMachine
> Added rotations to BlockMachine

- src/main/java/muramasa/antimatter/capability/impl/FluidHandlerItemCell.java
- src/main/java/muramasa/antimatter/capability/impl/MachineEnergyHandler.java
- src/main/java/muramasa/antimatter/capability/impl/MachineItemHandler.java
- src/main/java/muramasa/antimatter/capability/impl/MachineRecipeHandler.java
- src/main/java/muramasa/antimatter/gui/container/ContainerMachine.java
- src/main/java/muramasa/antimatter/gui/screen/ScreenBasicMachine.java
- src/main/java/muramasa/antimatter/item/ItemFluidCell.java
- src/main/java/muramasa/antimatter/machine/BlockMachine.java
- src/main/java/muramasa/antimatter/machine/Tier.java
- src/main/java/muramasa/antimatter/material/Material.java
- src/main/java/muramasa/antimatter/recipe/ItemWrapper.java
- src/main/java/muramasa/antimatter/recipe/RecipeInput.java
- src/main/java/muramasa/antimatter/tile/TileEntityMachine.java
Working recipe loading. It still has some duplicates but that shouldn't be too bad to fix.
What was added/fixed:
ItemCells changed just to compile, not working yet.
RecipeMap works along machines.
Machine state is synced.
GUI is synced.
And some small stuff
> Workable recipes, overclock, refactor MaterialRecipeLoader, fix map

- .gitignore
- .gitmodules
- README.md
- build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
As suggested on the Discord, here's something to replace the side folder stuff.
**Proposal:** use submodules 😃
> Buildscript cleanup

- build.gradle
- settings.gradle
> Allow gradle to compile

- src/main/java/muramasa/antimatter/capability/EnergyHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineCoverHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineEnergyHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineItemHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineRecipeHandler.java
- src/main/java/muramasa/antimatter/cover/CoverInstance.java
- src/main/java/muramasa/antimatter/cover/CoverOutput.java
- src/main/java/muramasa/antimatter/gui/SlotType.java
- src/main/java/muramasa/antimatter/gui/container/ContainerMachine.java
- src/main/java/muramasa/antimatter/gui/slot/SlotInput.java
- src/main/java/muramasa/antimatter/machine/BlockMachine.java
- src/main/java/muramasa/antimatter/machine/event/ContentEvent.java
- src/main/java/muramasa/antimatter/machine/event/MachineEvent.java
- src/main/java/muramasa/antimatter/tile/TileEntityStorage.java
- src/main/java/muramasa/antimatter/tile/pipe/TileEntityPipe.java
Fix tons of issues but now tesseract, items, energy works (hopefully). Need review
> Fix guis, energy transfer and recipes etc.

- build.gradle
- settings.gradle
- version/build.gradle
- version/gradle.properties
- version/version.properties
Trying to make a working buildscript
> Refractor buildscript

- src/main/java/muramasa/antimatter/capability/machine/MachineEnergyHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineFluidHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineInteractHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineItemHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineRecipeHandler.java
- src/main/java/muramasa/antimatter/gui/GuiData.java
- src/main/java/muramasa/antimatter/gui/SlotType.java
- src/main/java/muramasa/antimatter/gui/slot/SlotCell.java
- src/main/java/muramasa/antimatter/machine/MachineFlag.java
- src/main/java/muramasa/antimatter/machine/types/Machine.java
- src/main/java/muramasa/antimatter/tile/TileEntityMachine.java
Adds first usable generator.
TO test, place bucket of steam in steam generator, it outputs energy on all sides.
> Fix first generator & some small import  fixes.

- build.gradle
- gradle.properties
- settings.gradle
- src/main/java/muramasa/antimatter/capability/EnergyHandler.java
> Fix idea build

- src/main/java/muramasa/antimatter/capability/fluid/FluidResourceMachineRecipeHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineItemHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineRecipeHandler.java
- src/main/java/muramasa/antimatter/machine/types/Machine.java
- src/main/java/muramasa/antimatter/recipe/Recipe.java
- src/main/java/muramasa/antimatter/recipe/RecipeBuilder.java
- src/main/java/muramasa/antimatter/recipe/RecipeInput.java
- src/main/java/muramasa/antimatter/recipe/RecipeInputFlat.java
- src/main/java/muramasa/antimatter/recipe/RecipeMap.java
- src/main/java/muramasa/antimatter/recipe/TagInput.java
- src/main/java/muramasa/antimatter/tile/multi/TileEntityBasicMultiMachine.java
Same as for GregTech, first working tag map.
> First working version of tags.

- src/main/java/muramasa/antimatter/capability/machine/MachineItemHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineRecipeHandler.java
- src/main/java/muramasa/antimatter/material/MaterialTypeBlock.java
- src/main/java/muramasa/antimatter/material/MaterialTypeItem.java
- src/main/java/muramasa/antimatter/recipe/RecipeMap.java
- src/main/java/muramasa/antimatter/tile/TileEntityMachine.java
Add some convenience methods for tags(just what Rong had but without requiring a MaterialItem)
add null checks for caps
> Bugfix caps & fix tag convenience methods

- src/main/java/muramasa/antimatter/capability/EnergyHandler.java
- src/main/java/muramasa/antimatter/capability/machine/MachineRecipeHandler.java
Steam generator broke due to some checks, now it generates power.
> Fix steam generator so that it actually generates power
